### ISSUE TITLE
can't download the model

### ISSUE THREAD

**Issue by yinglili666** [kglore/llnet_color#5]
hello, thanks for your work, but I can't download your model on dropbox, could you provide another link? thanks!

**Comment by kglore** [comment]
Hi, I've added a Google Drive link. Sorry for the late response, I wasn't aware of this issue you opened!

https://drive.google.com/file/d/1bdpG7P1Zaf0HkJIBKoirvvk9ZxFBOomb/view?usp=sharing
(This link generated as of 1/20/2021).
